duh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from duh import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^coc/$', views.coc, name='coc'),
    url(r'^accessibility/$', views.accessibility, name='accessibility'),
    url(r'^travel/$', views.travel, name='travel'),
    url(r'^blog/', include('tinyblog.urls', namespace='blog')),
    #url(r'^attendees/$', views.attendees, name='attendees'),
    url(r'^talks/$', views.talks, name='talks'),
    url(r'^scholarship/$', views.scholarship, name='scholarship'),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^sprints/$', views.sprints, name='sprints'),
    url(r'^live/$', views.livestream, name='livestream'),
    url(r'^dinners/$', views.dinners, name='dinners'),
    url(r'^team/', include('organizers.urls', namespace='organizers')),
    url(r'^tickets/', include('lottery.urls')),
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^slack/', include('slakslakslak.urls', namespace='slakslakslak')),
    url(r'^r/', include('rocks.urls', namespace='rocks')),
]

# Serve uploaded files in DEBUG mode
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lottery/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^signup$', views.signup, name='signup'),
    url(r'^thank-you/(?P<email>.*)$', views.signup_confirmation, name='signup_confirmation'),
    url(r'^closed$', views.registration_closed, name='registration_closed'),
]

tinyblog/urls.py
from django.conf.urls import url

from .views import post_detail, post_list

urlpatterns = [
    url(r'^$', post_list, name='index'),
    url(r'^article/(?P<slug>[-\w]+)/$', post_detail, name='article'),
]

lottery/models.py
from datetime import timedelta

from django.db import models
from django.db.transaction import atomic
from django.utils import timezone

RSVP_VALIDITY_HOURS = 72

INDIVIDUAL_TICKET = 'individual'
CORPORATE_TICKET = 'corporate'
TICKET_TYPE_CHOICES = [
    (INDIVIDUAL_TICKET, 'Individual Ticket'),
    (CORPORATE_TICKET, 'Corporate Ticket'),
]


class Batch(models.Model):
    created_at = models.DateTimeField(default=timezone.now)
    assigned_at = models.DateTimeField(null=True, blank=True)
    name = models.CharField(max_length=200)
    tickets = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = 'batches'

    def __str__(self):
        return self.name

    @property
    def assigned(self):
        return bool(self.assigned_at)

    @property
    def expires_at(self):
        if not self.assigned:
            return None

        return self.assigned_at + timedelta(hours=RSVP_VALIDITY_HOURS)

    @atomic
    def assign_participants(self):
        if self.assigned:
            raise ValueError('Batch %s has already been assigned' % self.id)

        self.assigned_at = timezone.now()
        self.save()

        ids_query = Participant.objects.filter(batch=None).order_by('?')[:self.tickets]
        return Participant.objects.filter(id__in=ids_query).update(batch=self)


class Participant(models.Model):
    created_at = models.DateTimeField(default=timezone.now)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    ticket_type = models.CharField(max_length=200, choices=TICKET_TYPE_CHOICES)
    batch = models.ForeignKey(Batch, null=True, blank=True, related_name='participants')

    def __str__(self):
        return self.email

    @property
    def individual(self):
        return self.ticket_type == INDIVIDUAL_TICKET

    @property
    def corporate(self):
        return self.ticket_type == CORPORATE_TICKET

lottery/forms.py
import html2text
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string

from .models import Participant


class ParticipantSignupForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = ['first_name', 'last_name', 'email', 'ticket_type']

    def clean_email(self):
        email = self.cleaned_data['email']
        return email.strip().lower()
        
    def save(self):
        participant = super(ParticipantSignupForm, self).save()
        if participant:
            html_message = render_to_string('lottery/email_confirmation.html')
            message = html2text.html2text(html_message)
            send_mail(
                subject="Django: Under The Hood 2016 ticket lottery confirmation",
                message=message,
                from_email=settings.SERVER_EMAIL,
                recipient_list=[participant.email],
                fail_silently=True,
                html_message=html_message
            )
        return participant

lottery/views.py
from functools import wraps

from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone

from .models import Participant
from .forms import ParticipantSignupForm


def timestamped(view):
    """
    Injects a current datetime on the request object at `request.timestamp`.
    Makes testing time-dependent views easy: just pass `timestamp` as kwarg to `get` or `post`.
    """

    @wraps(view)
    def wrapper(request, *args, **kwargs):
        request.timestamp = request.environ.get('timestamp', timezone.now())
        return view(request, *args, **kwargs)

    return wrapper


@timestamped
def signup(request):
    if not settings.REGISTRATION_START <= request.timestamp <= settings.REGISTRATION_END:
        return redirect('registration_closed')

    if request.method == 'POST':
        form = ParticipantSignupForm(request.POST)
        if form.is_valid():
            participant = form.save()
            return redirect('signup_confirmation', email=participant.email)
    else:
        form = ParticipantSignupForm()

    return render(request, 'lottery/signup.html', {'form': form})


def signup_confirmation(request, email):
    participant = get_object_or_404(Participant, email=email)
    return render(request, 'lottery/signup_confirmation.html', {'participant': participant})


@timestamped
def registration_closed(request):
    return render(request, 'lottery/registration_closed.html', {
        'now': request.timestamp,
        'start': settings.REGISTRATION_START,
        'end': settings.REGISTRATION_END,
    })

lottery/templates/lottery/email_confirmation.html
<p>
    Hello! ✨
</p>
<p>
    This is a confirmation that your email has been added to 2016 Django: Under
    the Hood ticket lottery. 🎟🎲
</p>
<p>
    <strong>What happens now?</strong>
</p>
<p>
    Sit back and relax! ⛱
</p>
<p>
    We will start inviting the first batch on Thursday July 28th at noon CET,
    and successive batches in the days or weeks after.
</p>
<p>
    Note that if you are invited, you have 72 hours to actually confirm and 
    pay for your ticket, or it will be assigned to someone else.
</p>

<p>
    We're hoping we'll see you in Amsterdam!<br />
    Django: Under The Hood Team
</p>

lottery/templates/lottery/registration_closed.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h1><img src="{% static 'img/tickets-header.png' %}" class="header-image" alt="TICKETS" /></h1>
    {% if start > now %}
        <h2>Sorry, registration is not opened yet! 🔜</h2>
        <p>
            Registration for Django: Under The Hood starts on {{ start }}
            and will continue until {{ end }}. ✨
        </p>
        
        <h3>Timeline 📅</h3>
        <ol>
            <li><strong>On Tuesday, July 12, we will open registration.</strong>
            You'll have two weeks to submit your e-mail address for the lottery here, until 
            July 26th at noon CET.</li>

            <li><strong>On Thursday July 28th at noon CET we're going to randomly select attendees 
            who will receive a link to purchase their conference tickets.</strong> This link will be
            valid for 72 hours, and then we will randomly assign it to another attendee until
            all of the tickets have been purchased.</li>
        </ol>
        
        <h3>Pricing 💶</h3>
        <p>
            For 2016, the full conference passes including 1.5 day of Talks and 1.5 of 
            contributing to Open Source alongside core team will have the following pricing:
        </p>

        <ul>
            <li>200€ for individual attendees (paying out of their own pocket) </li>
            <li>300€ for corporate tickets (companies buying tickets for their employees)</li>
        </ul>
        
        <h3>Reserve tickets for your team 👧👦👧</h3>
        <p>
            If you want to make sure that tickets for your team are reserved and set aside,
            we'd be happy to discuss a sponsorship opportunity with you. Please get in touch
            with us on <a href="mailto:hello@djangounderthehood.com">hello@djangounderthehood.com</a>
        </p>

    {% endif %}

    {% if now > end %}
        <h1>Django: Under The Hood is almost sold out!</h1>
        <p>
            Almost 300 fantastic developers signed up for our event already.
            We're releasing one, tiny batch of tickets on general sale on 
            <a href="http://time.is/1500_16_August_2016_in_Amsterdam" target="_blank">
            Tuesday, 16th of July at 3pm Amsterdam time</a>. 
        </p>
        <p>
            To buy tickets on Tuesday, click here:
        </p>
        <p style="text-align: center; margin-bottom: 20px">
            <a class="btn" href="https://ti.to/duth/2016">Go to registration</a>
        </p>
        <p>
            If you need more tickets for your team, we may still
            have some sponsorships slots available. Get in touch:
            <a href="mailto:hello@djangounderthehood.com">hello@djangounderthehood.com</a>.
        </p>
    {% endif %}

    <h3>Details 📰</h3>
    <p>
        You can read more about the registration process on
        <a href="{% url 'blog:article' slug='2016-07-01-registration' %}">our blog</a>.
    </p>
{% endblock %}

lottery/templates/lottery/signup.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h1><img src="{% static 'img/tickets-header.png' %}" class="header-image" alt="TICKETS" /></h1>
    <h2>2016 Registration 🎟🎲</h2>

    <p>Enter your data below to sign up for our <a href="#how-it-works">ticket lottery</a> 🎟🎲. You can read more about it on
    <a href="{% url 'blog:article' slug='2016-07-01-registration' %}">our blog</a>.</p>
    
    <p>We ask for only one submission per person. If multiple employees of your company want to come, they must each individually submit.</p>

    <form method="post" action="{% url 'signup' %}" class="form--signup">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="cls"></div>
        <input type="submit" value="Sign up!" />
    </form>
    
    <h3 id="how-it-works">How it works? 🤔</h3>
    <p>
        <strong>Registration for ticket lottery is open until <a href="http://time.is/1200_26_July_2016_in_Amsterdam">Tuesday, July 26th at noon CEST</a>.</strong>
    </p>
    <p>
        On <a href="http://time.is/1200_28_July_2016_in_Amsterdam">Thursday July 28th at noon CEST</a> we're going to randomly select attendees 
        who will receive a link to purchase their conference tickets.</strong> This link will be
        valid for 72 hours, and then we will randomly assign it to another attendee until
        all of the tickets have been purchased.</li>
    </ol>
    
    <h3>Pricing 💶</h3>
    <p>
        For 2016, the full conference passes including 1.5 day of Talks and 1.5 of 
        contributing to Open Source alongside core team will have the following pricing:
    </p>

    <ul>
        <li>200€ for individual attendees (paying out of their own pocket) </li>
        <li>300€ for corporate tickets (companies buying tickets for their employees)</li>
    </ul>
    
    <h3>Reserve tickets for your team 👧👦👧</h3>
    <p>
        If you want to make sure that tickets for your team are reserved and set aside,
        we'd be happy to discuss a sponsorship opportunity with you. Please get in touch
        with us on <a href="mailto:hello@djangounderthehood.com">hello@djangounderthehood.com</a>
    </p>
{% endblock %}

lottery/templates/lottery/signup_confirmation.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h1><img src="{% static 'img/tickets-header.png' %}" class="header-image" alt="TICKETS" /></h1>
    <h2>Thanks! 💖</h2>

    <p>You're now registered for the ticket lottery with email: <strong>{{ participant.email }}</strong>.</p>
    <p>
        If this email is incorrect, please <a href="mailto:hello@djangounderthehood.com">
        let us know</a>!
    </p>
    
    <h3>What happens now? 🔜</h3>
    <p>
        Sit back and relax! ⛱
    </p>
    <p>
        We will start inviting the first batch on Thursday July 28th at noon CET,
        and successive batches in the days or weeks after.
    </p>
    <p>
        Note that if you are invited, you have 72 hours to actually confirm and 
        pay for your ticket, or it will be assigned to someone else.
    </p>
{% endblock %}