duh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from duh import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^coc/$', views.coc, name='coc'),
    url(r'^accessibility/$', views.accessibility, name='accessibility'),
    url(r'^travel/$', views.travel, name='travel'),
    url(r'^blog/', include('tinyblog.urls', namespace='blog')),
    #url(r'^attendees/$', views.attendees, name='attendees'),
    url(r'^talks/$', views.talks, name='talks'),
    url(r'^scholarship/$', views.scholarship, name='scholarship'),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^sprints/$', views.sprints, name='sprints'),
    url(r'^live/$', views.livestream, name='livestream'),
    url(r'^dinners/$', views.dinners, name='dinners'),
    url(r'^team/', include('organizers.urls', namespace='organizers')),
    url(r'^tickets/', include('lottery.urls')),
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^slack/', include('slakslakslak.urls', namespace='slakslakslak')),
    url(r'^r/', include('rocks.urls', namespace='rocks')),
]

# Serve uploaded files in DEBUG mode
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizers/urls.py
from django.conf.urls import url

from .views import ListView

urlpatterns = [
    url(r'^$', ListView.as_view(), name='list'),
]

schedule/urls.py
from django.conf.urls import url

from .views import ScheduleView, IcalTalkScheduleView

urlpatterns = [
    url(r'^$', ScheduleView.as_view(), name='schedule'),
    url(r'^talks/ical/$', IcalTalkScheduleView.as_view(), name='talks-ical'),
]

tinyblog/urls.py
from django.conf.urls import url

from .views import post_detail, post_list

urlpatterns = [
    url(r'^$', post_list, name='index'),
    url(r'^article/(?P<slug>[-\w]+)/$', post_detail, name='article'),
]

attendees/models.py
from django.db import models
from django.utils.crypto import salted_hmac

from django_gravatar.helpers import get_gravatar_url


class AttendeeQuerySet(models.QuerySet):
    def visible(self):
        return self.filter(visible=True).exclude(category=Attendee.CATEGORY.TEST)


class ATTENDEE_CATEGORY:
    REGULAR = 'regular'
    SPEAKER = 'speaker'
    CORE = 'core'
    SPONSOR = 'sponsor'
    TEST = 'test'

    choices = [
        (REGULAR, REGULAR),
        (SPEAKER, SPEAKER),
        (CORE, CORE),
        (SPONSOR, SPONSOR),
        (TEST, TEST),
    ]

    @classmethod
    def guess(cls, ticket_name):
        """
        Try and guess the category based on the name of the ticket (
        "Sponsor Ticket (foobar)", "Regular ticket", ...)
        """
        if not ticket_name:
            return cls.REGULAR
        s = ticket_name.split()[0]
        try:
            return getattr(cls, s.upper())
        except AttributeError:
            return cls.REGULAR


class Attendee(models.Model):
    CATEGORY = ATTENDEE_CATEGORY
    reference = models.CharField(max_length=6, null=False, blank=False)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    twitter = models.CharField(max_length=100, null=True, blank=True)
    visible = models.BooleanField(default=False)
    category = models.CharField(max_length=10, choices=CATEGORY.choices, default=CATEGORY.REGULAR)

    objects = AttendeeQuerySet.as_manager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.twitter == '-':
            self.twitter = None
        elif self.twitter:
            self.twitter = self.twitter.replace('@', '').replace('twitter.com/', '')
        return super(Attendee, self).save(*args, **kwargs)

    def update_with_data(self, data):
        for attr, value in data.items():
            setattr(self, attr, value)
        self.save()

    @property
    def hashed_email(self):
        """
        Return a hash (hex string) of the attendee's email.
        """
        key_salt = self.__class__.__name__
        return salted_hmac(key_salt, self.email).hexdigest()

    @property
    def avatar(self):
        default = 'http://api.adorable.io/avatar/100/%s.png' % (self.hashed_email)
        return get_gravatar_url(self.email.lower(), default=default, size=100)

sponsors/models.py
import re

from django.db import models
from django.utils.html import format_html
from django.utils import timezone


class SPONSOR_LEVELS:
    H1 = 'h1'
    H2 = 'h2'
    H3 = 'h3'
    PARTNER = 'partner'

    choices = [
        (H1, '<h1>'),
        (H2, '<h2>'),
        (H3, '<h3>'),
        (PARTNER, 'Partner')
    ]


class SponsorQueryset(models.QuerySet):
    def h1(self):
        return self._by_level(SPONSOR_LEVELS.H1)

    def h2(self):
        return self._by_level(SPONSOR_LEVELS.H2)
        
    def h3(self):
        return self._by_level(SPONSOR_LEVELS.H3)

    def partner(self):
        return self._by_level(SPONSOR_LEVELS.PARTNER)

    def _by_level(self, level):
        return self.filter(level=level).order_by('?')

    def live(self):
        return self.filter(is_live=True)


class Sponsor(models.Model):
    LEVELS = SPONSOR_LEVELS

    level = models.CharField(max_length=20, choices=LEVELS.choices)
    name = models.CharField(max_length=200)
    description = models.TextField(
        blank=True, help_text="Use `[[link text]]` to create a link to the sponsor's URL.")
    logo = models.ImageField(blank=True, upload_to='sponsors/%Y/')
    url = models.URLField(blank=True)
    created_on = models.DateTimeField(default=timezone.now, editable=False)
    is_live = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)

    objects = SponsorQueryset.as_manager()

    def __str__(self):
        return self.name

    @property
    def linkified_description(self):
        """
        Replaces [[foo]] with <a href="{{ self.url }}">foo</a>.
        Also supports the [[http://example.com|foo]] syntax to generate
        <a href="http://example.com">foo</a>
        """
        links = []
        def linkify(matchobj, links=links):
            if '|' in matchobj.group(1):
                url = matchobj.group(1).split('|')
                link = format_html('<a href="{0}" target="_blank">{1}</a>', url[0], url[1])
            else:
                link = format_html('<a href="{0}" target="_blank">{1}</a>', self.url, matchobj.group(1))
            links.append(link)
            return '{%d}' % (len(links) - 1)

        fmt = re.sub(r'\[\[([^\]]+)\]\]', linkify, self.description)
        return format_html(fmt, *links)

    @property
    def logo_html(self):
        if self.logo:
            return format_html('<img class="logo" src="{0}" alt="{1}" title="{1}"/>', self.logo.url, self.name)
        return format_html('<span class="nologo">{0}</span>', self.name)

attendees/views.py
from django.shortcuts import render

# Create your views here.

templates/_footer.html
{% load staticfiles credits %}

<div class="row">
    <div class="col-md-12">
        <img src="{% static 'img/contact-header.png' %}" class="header-image" alt="CONTACT" height="120" />
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        Got a question?<br /> Drop us a line: <a href="mailto:hello@djangounderthehood.com">hello@djangounderthehood.com</a>
    </div>
    <div class="col-md-3">
      <a href="http://twitter.com/DjangoUnderHood">@DjangoUnderHood</a>
    </div>
</div>

<p class="credits row"><span data-emoji-alt="🎸🚗">Django: Under The Hood</span> conference is organized by <a href="{% url 'organizers:list' %}" data-emoji-alt="👫👭👬👫👬👫">bunch of stroopwafel enthusiasts</a> with help from the <span data-emoji-alt="🌷🎸👬👭">Dutch Django Association</span>.</p>

<p class="easteregg row text-center">
    <a title="Turn on emoji mode" class="emojimode-toggler emojimode-off">😺</a>
</p>

templates/_nav.html
{% load staticfiles %}

<ul>
	<li><a href="{% url 'talks' %}" data-emoji-alt="🕒">Talk videos</a></li>
	{# <li><a href="{% url 'signup' %}" data-emoji-alt="🎫">Tickets</a></li> #}
	<li><a href="{% url 'schedule:schedule' %}" data-emoji-alt="🕒">Schedule</a></li>
	<li><a href="{% url 'sprints' %}" data-emoji-alt="🏃">Sprints</a></li>
	<li><a href="{% url 'home' %}#speakers" data-emoji-alt="📢">Speakers</a></li>
	<li><a href="{% url 'home' %}#sponsors" data-emoji-alt="💞">Sponsors</a></li>
	<li><a href="{% url 'travel' %}" data-emoji-alt="🚀">Travel</a></li>
	<li><a href="{% url 'accessibility' %}" data-emoji-alt="♿">Accessibility</a></li>
	{# <li><a href="{% url 'scholarship' %}">Scholarship</a></li> #}
	<li><a href="{% url 'coc' %}">Code of Conduct</a></li>
	<li><a href="{% url 'blog:index' %}" data-emoji-alt="📖">Blog</a></li>
	<li><a class="stroopwafelify" title="Stroop">🍯🍪🌧</a></li>
</ul>

templates/_sponsors.html
{% load staticfiles sponsors %}

{% if sponsors.count > 0 %}
<div class="row">
    <div class="col-md-12">
        <img src="{% static 'img/sponsors-header.png' %}" class="header-image" alt="SPONSORS" />
    </div>
</div>
{% endif %}

{% if sponsors.h1.count > 0 %}<h3>Gold sponsors</h3>{% endif %}
{% for chunk in sponsors.h1|chunkify:2 %}
    <div class="row vertical-center">
    {% for sponsor in chunk %}
        <div class="sponsor gold col-md-6 {% if not sponsor.is_live %}preview{% endif %} vertical-center">
            {% if user.is_staff %}
                <a class="toolbox" href="{% url 'admin:sponsors_sponsor_change' sponsor.pk %}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
            {% endif %}
            <a href="{{ sponsor.url }}" target="_blank">
                {{ sponsor.logo_html }}
            </a>
        </div>
    {% endfor %}
    </div>
{% endfor %}

{% if sponsors.h2.count > 0 %}<h3>Silver sponsors</h3>{% endif %}
{% for chunk in sponsors.h2|chunkify:3 %}
    <div class="row vertical-center">
    {% for sponsor in chunk %}
        <div class="sponsor silver col-md-4 {% if not sponsor.is_live %}preview{% endif %}">
            {% if user.is_staff %}
                <a class="toolbox" href="{% url 'admin:sponsors_sponsor_change' sponsor.pk %}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
            {% endif %}
            <a href="{{ sponsor.url }}" target="_blank">
                {{ sponsor.logo_html }}
            </a>
        </div>
    {% endfor %}
    </div>
{% endfor %}

{% if sponsors.h3.count > 0 %}<h3>Bronze sponsors</h3>{% endif %}
{% for chunk in sponsors.h3|chunkify:4 %}
    <div class="row vertical-center">
    {% for sponsor in chunk %}
        <div class="sponsor silver col-md-3 {% if not sponsor.is_live %}preview{% endif %}">
            {% if user.is_staff %}
                <a class="toolbox" href="{% url 'admin:sponsors_sponsor_change' sponsor.pk %}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
            {% endif %}
            <a href="{{ sponsor.url }}" target="_blank">
                {{ sponsor.logo_html }}
            </a>
        </div>
    {% endfor %}
    </div>
{% endfor %}

{% if sponsors.partner.count > 0 %}<h3>Partners</h3>{% endif %}
{% for chunk in sponsors.partner|chunkify:3 %}
    <div class="row vertical-center">
    {% for sponsor in chunk %}
        <div class="sponsor partner col-md-4 {% if not sponsor.is_live %}preview{% endif %}">
            {% if user.is_staff %}
                <a class="toolbox" href="{% url 'admin:sponsors_sponsor_change' sponsor.pk %}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
            {% endif %}
            <a href="{{ sponsor.url }}" target="_blank">
                {{ sponsor.logo_html }}
            </a>
            {{ sponsor.linkified_description|linebreaks }}
        </div>
    {% endfor %}
    </div>
{% endfor %}

{% comment %}
<div class="row">
    <img src="{% static 'img/supportus-header.png' %}" class="header-image" alt="Support Us" />
    <div class="col-md-12">
        <p>We are seeking companies who wish to support the event financially. Your help will contribute to making the event as affordable as possible for everyone, as well as letting us bring many of the Django team members to the event to share knowledge and improve the Django development process. If you are interested in helping, please <a href="mailto:hello@djangounderthehood.com">get in touch</a>.</p>
    </div>
</div>
{% endcomment %}

templates/_tickets.html
{% load staticfiles %}

<div class="row">
    <div class="col-md-12">
        <img src="{% static 'img/tickets-header.png' %}" class="header-image" alt="TICKETS" />
        <p>
            The conference tickets are now sold out. <a href="https://ti.to/duth/2016">Join the Waiting List</a> for last minute cancellations.
        </p>
        {% comment %}
        <div class="countdown" data-target="{{ ticket_sale_start.isoformat }}">
            <div class="countdown-past{% if now >= ticket_sale_start %} hidden{% endif %}">
                <p>Conference <span data-emoji-alt="🎫">registration</span> will open on 12th July 2016 at noon CET.</p>
                
                <p>🎫 <a href="/blog/article/2016-07-01-registration/">Read on our blog how we plan to sell conference tickets this year</a>.</p>

                <p>If you want to have <span data-emoji-alt="🎫">tickets</span> for your team reserved, please scroll down to learn about the <span data-emoji-alt="💞">sponsorship</span> opportunities.</p>

                <h4>Get notified when <span data-emoji-alt="🎫">tickets</span> go on sale:</h4>

                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <form action="//djangounderthehood.us8.list-manage.com/subscribe/post?u=7e08f3e7ba2446210dc2f72fb&amp;id=3445b272c8" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-inline" target="_blank" novalidate>
                            <input type="email" value="" name="EMAIL" class="required email form-control" placeholder="Your e-mail" id="mce-EMAIL">

                            <div style="position: absolute; left: -5000px;"><input type="text" name="b_7e08f3e7ba2446210dc2f72fb_3445b272c8" tabindex="-1" value=""></div>
                            <input type="submit" value="Let me know" class="form-control" />
                        </form>
                    </div>
                </div>
            </div>
            <div class="countdown-future{% if now < ticket_sale_start %} hidden{% endif %}">
                <p><span data-emoji-alt="🎫">Tickets</span> are now available.</p>

                <p class="centered"><a href="{% url 'signup' %}" class="btn btn-large btn-primary">Sign up for tickets now!</a></p>
            </div>
        </div>
        {% endcomment %}
    </div>
</div>

templates/accessibility.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<section id="accessibility">
    <img src="{% static 'img/accessibility-header.png' %}" class="header-image" alt="Accessibility" />

    <h3>Conference venue</h3>
    <p>
        The conference venue, Pakhuis de Zwijger, has complete step free access.
        All doorways are wide enough to accommodate wheelchairs and
        an elevator is present to reach all floors.
        An accessible toilet is available, but please contact us in advance if you may need this,
        so that the venue can make arrangements.
    </p>
    <p>
        You can reach the conference venue with a tram and bus that stop directly in front of the
        building. Almost all trams and buses in Amsterdam have a low step entry and are suitable for
        wheelchairs without requiring advance notification. Advance notification is required
        if you are travelling with a wheelchair on a train. Some of the trains have low step entry, for
        others staff will provide a ramp if booked in advance.
    </p>
    <p>
        No special facilities are available for attendees with visual or auditory impairments.
        If you have special requests for this, or any other area, please get in touch with us
        and we'll see what we can do.
    </p>

    <h3>Sprint venue</h3>
    <p>
        The sprint venue has step free access through an alternate entrance. Please let us know in advance
        if you will be requiring this so that we can make arrangements.
    </p>

    <h3>Dietary requirements</h3>
    <p>
        For attendees with vegan and gluten free diets, special meals are available at Pakhuis de Zwijger.
        Please ask the staff for these. At the sprints we'll be providing a variety of foods and also a gluten/lactose
        free and a vegan soup.
    </p>
    
    <h3>Live captioning</h3>
    <p>
        All talks presented during the conference will feature simultaneous speech-to-text transcription, 
        which will also be used for subtitling the conference videos that are subsequently published.
    </p>

</section>

{% endblock %}

templates/attendees.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<section id="coc" class="row">
    <div class="col-md-12">
        <h2>
            <img src="{% static 'img/icons/people.png' %}" alt="People" />
            Who's coming?
        </h2>
    </div>
    <div class="cls"></div>

    <div id="attendees">
        <div class="row">
            {% for attendee in attendees %}
            <div class="col-md-4">
                <img src="{{ attendee.avatar }}" class="attendee" alt="{{ attendee.name }}" />
                <h4>
                    {{ attendee.name }}
                </h4>
                {% if attendee.twitter %}
                <p>
                    <a href="http://twitter.com/{{ attendee.twitter }}">@{{ attendee.twitter }}</a>
                </p>
                {% endif %}
            </div>
            {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

templates/base.html
{% load staticfiles %}
{% load pipeline %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Django: Under the Hood{% endblock %}</title>

        <meta name="description" content="Django: Under the Hood is an exciting conference full of deep, detailed talks about Django taking place in November, 2016, Amsterdam. Come and learn about the internals of Django, and help to shape its future.">
        <meta name="keywords" content="programming, python, django, conference, under the hood">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta property="og:title" content="Django: Under the Hood 2016" />
        <meta property="og:type" content="website" />
        <meta property="og:description" content="Django: Under the Hood is an exciting conference full of deep, detailed talks about Django taking place in November, 2016, Amsterdam. Come and learn about the internals of Django, and help to shape its future." />
        <meta property="og:url" content="https://www.djangounderthehood.com/" />
        <meta property="og:image" content="https://www.djangounderthehood.com/static/img/avatar.png" />

        <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}" />
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" media="screen">
        <link rel="stylesheet" href="//brick.a.ssl.fastly.net/Lora:400,700,400i,700i">
        {% stylesheet 'app' %}
    </head>
    <body>
        <div id="left-fixed-cloud"></div>
        {% block right_cloud %}<div id="right-absolute-cloud"></div>{% endblock %}
        <div class="container">
            <aside>
              <a href="{% url 'home' %}">
                  <img src="{% static 'img/logo-watercolor.png' %}" alt="Django: Under the Hood" class="logo" />
              </a>
              <p>
                3 - 6th Nov 2016<br />
                <span data-emoji-alt="🌷">Amsterdam</span>
              </p>
              <nav>
                  {% include '_nav.html' %}
              </nav>
            </aside>
            <main>
                <header class="hidden-xs hidden-print"></header>

                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">
                            {{ message }}
                        </li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% block content %}{% endblock %}
                <div class="cls"></div>
                <footer>
                    {% include '_footer.html' %}
                </footer>
            </main>
        </div>

        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        {% javascript 'vendor' %}
        {% javascript 'app' %}
        <script type="text/javascript">
            window.stroopwafel = "{% static 'img/stroopwafel.png' %}";
            window.glutenfree = "{% static 'img/logo-watercolor.png' %}";
        </script>
    </body>
</html>

templates/coc.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<section id="coc" class="row">
    <img src="{% static 'img/coc-header.png' %}" class="header-image" alt="Code of Conduct" height="120" />
    <p>
        <em>Django: Under The Hood</em> aims to be a welcoming event, where people
        meet in a friendly environment. Accordingly, all participants are expected
        to show respect and courtesy to other participants throughout the conference.
    </p>
    <p>
        To make clear what is expected, all delegates/attendees, speakers,
        exhibitors, organizers and volunteers at any Django: Under The Hood event
        are required to conform to the following Code of Conduct. Organizers will
        enforce this code before and throughout the event.
    </p>

    <h3 id="tldr">In short</h3>
    <ul>
        <li>Django: Under The Hood is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, sexual orientation, disability, physical appearance, body size, race, or religion.</li>
        <li>We do not tolerate harassment of conference participants in any form.</li>
        <li>Sexual language and imagery are not appropriate for any conference venue, including talks, evening events, and the conference hotel.</li>
        <li>Be kind to others. Do not insult or put down other attendees. Behave professionally. Don’t publish individual photographs of people without their consent. Remember that harassment and sexist, racist, or exclusionary jokes are not appropriate for Django: Under The Hood.</li>
        <li>Conference participants violating these rules may be sanctioned or expelled from the conference without a refund at the discretion of the conference organizers.</li>
    </ul>
    <h3 id="longer-version">Longer version</h3>
    <p>Harassment includes offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.</p>

    <p>Participants asked to stop any harassing behavior are expected to comply immediately.

    <p>Be careful in the words that you choose. Remember that sexist, racist, and other exclusionary jokes can be offensive to those around you. Excessive swearing and offensive jokes are not appropriate for Django: Under The Hood.</p>

    <p>If a participant engages in harassing behavior, the conference organizers may take any action they deem appropriate, including warning the offender or expulsion from the conference with no refund.</p>

    <p>We expect participants to follow these rules at all conference venues, the conference hotel, and conference-related social events.</p>

    <h3 id="reporting-harassment">Reporting harassment</h3>

    <p>If you are being harassed, noticed that someone else is being harassed, or have any other concerns, please contact one of the organizers immediately either in person, or by sending email to <a href="mailto:conduct@djangounderthehood.com">conduct@djangounderthehood.com</a>.</p>

    <p>If the matter is especially urgent, please call Django: Under The Hood staff:
        <ul>
            <li>Female staff member: <strong>+31 683 458 027</strong></li>
            <li>Male staff member: <strong>+31 651 289 058</strong></li>
       </ul>
    </p>

    <p>If you’re currently afraid of your physical safety or are in danger, contact local law enforcement in the Netherlands:
        <ul><li>Emergency (Fire, Medical, Police): 112</li></ul>
    </p>

    <p>
        The staff is well informed on how to deal with the incident and how to further proceed with the situation. Conference staff will be happy to help participants contact hotel/venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the conference. We value your attendance.
    </p>
</section>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<section id="about">
    {% include '_about.html' %}
</section>
<div class="cls"></div>

<section id="speakers">
    {% include '_speakers.html' %}
</section>

{% comment %}
<section id="testimonials">
    {% include '_testimonials.html' %}
</section>
{% endcomment %}

<section id="tickets">
    {% include '_tickets.html' %}
</section>

<section id="sponsors">
    {% include '_sponsors.html' %}
</section>

{% endblock %}

templates/organizers_list.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load chunkify %}
{% load randomify %}
{% load toolbox %}

{% block content %}
<section id="organizers" class="row">
    <h1>Team</h1>

    {% for chunk in object_list|randomify_by_date|chunkify:3 %}
        <div class="row">
            {% for organizer in chunk %}
                <div class="organizer col-md-4 {% if not organizer.published %} preview{% endif %} clearfix" id="{{ organizer.slug }}">

                        {% if organizer.url %}<a href="{{ organizer.url }}">{% endif %}
                            {{ organizer.get_picture_html }}
                        {% if organizer.url %}</a>{% endif %}

                    <h3 class="name" {{ organizer.data_emoji_alt }}>{{ organizer.name }}</h3>
                    <p class="title">{{ organizer.title }}</p>
                    {% toolbox organizer user=user %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}
</section>
{% endblock %}

templates/scholarship.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<section id="scholarship" class="row">
    <img src="{% static 'img/scholarship-header.png' %}" class="header-image" alt="Scholarship" />

    <p>
        Django: Under The Hood is striving to provide a great experience for the most diverse group of people possible. We do believe in equality, and we invite everyone to participate. In order to make this possible, we are proud to announce our <strong>scholarship programme</strong> for people who would otherwise be unable to participate.
    </p>
    <p>
        Our scholarship fund will support about twenty people to attend Django: Under The Hood. Scholarships are fully sponsored (i.e. free) tickets that are awarded after an application process. Travel expenses and accommodation, if required, will also be awarded.
    </p>
    <p>
        Anyone from an underrepresented group in tech is invited to apply for this scholarship. This includes, but is not limited to:
    </p>
    <ul>
        <li>women and other gender minorities of all expressions and identities; e.g. trans, agender and non-binary</li>
        <li>people of color, including Indigenous/Native people</li>
        <li>sexuality minorities, including asexual people</li>
        <li>people with disabilities, both visible and invisible</li>
        <li>neurodiverse people</li>
        <li>people with chronic illnesses or diseases</li>
        <li>religious and ethnic minorities</li>
        <li>people who don't speak English as a first language</li>
        <li>undocumented people (US), naturalized people, and refugees</li>
        <li>age minorities (under 21, over 50)</li>
        <li>working class people and people experiencing poverty</li>
        <li>homeless and home/food insecure people</li>
        <li>caregivers of children or other dependents</li>
        <li>people who have experienced trauma and its aftermath (PTSD, anxiety, etc)</li>
        <li>people living with or recovering from substance abuse</li>
    </ul>
    <p>
        The application process is simple: Tell us about what you do with Python or Django, and why you want to attend Django: Under The Hood.
    </p>

    <p class="centered-margin">
        <a class="btn btn-primary active" href="https://docs.google.com/forms/d/1_OgV6xgTVmrNBrvnPYXcuUgPN0m8mdEwsNkAV818bx4/viewform">Apply now for a Django: Under The Hood Scholarship</a>
    </p>

    <p>Applications are due 23rd June, by the end of the day CEST (Amsterdam time).</p>

    <p>
        <b>Scholarships are made possible by our <a href="{% url 'home' %}#sponsors">generous sponsors</a>. We are proud to have these sponsors showing their support for our community. Thank you!</b>
    </p>

    <h3 id="important-dates">Important dates</h3>
    <ul>
        <li>9th of June: Call for submissions opens (a form will be linked on this page).</li>
        <li>23rd of June: Applications for the scholarship programme must be submitted in full.</li>
        <li>1st of July: Award recipients will be notified by email of their acceptance.</li>
    </ul>

    <p>Thank you <a href="http://2015.jsconf.eu/">JSConf EU</a> for providing a great example of the process we're adopting, and to <a href="http://www.alterconf.com/">AlterConf</a> for further inspiration.</p>
</section>

{% endblock %}