duh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from duh import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^coc/$', views.coc, name='coc'),
    url(r'^accessibility/$', views.accessibility, name='accessibility'),
    url(r'^travel/$', views.travel, name='travel'),
    url(r'^blog/', include('tinyblog.urls', namespace='blog')),
    #url(r'^attendees/$', views.attendees, name='attendees'),
    url(r'^talks/$', views.talks, name='talks'),
    url(r'^scholarship/$', views.scholarship, name='scholarship'),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^sprints/$', views.sprints, name='sprints'),
    url(r'^live/$', views.livestream, name='livestream'),
    url(r'^dinners/$', views.dinners, name='dinners'),
    url(r'^team/', include('organizers.urls', namespace='organizers')),
    url(r'^tickets/', include('lottery.urls')),
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^slack/', include('slakslakslak.urls', namespace='slakslakslak')),
    url(r'^r/', include('rocks.urls', namespace='rocks')),
]

# Serve uploaded files in DEBUG mode
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schedule/urls.py
from django.conf.urls import url

from .views import ScheduleView, IcalTalkScheduleView

urlpatterns = [
    url(r'^$', ScheduleView.as_view(), name='schedule'),
    url(r'^talks/ical/$', IcalTalkScheduleView.as_view(), name='talks-ical'),
]

schedule/models.py
from datetime import datetime, timedelta

import icalendar

from django.db import models
from django.utils import timezone


class EventQuerySet(models.QuerySet):
    def as_ical(self, **kwargs):
        calendar = icalendar.Calendar()
        for k, v in kwargs.items():
            calendar[k] = v
        for event in self:
            if event.is_blank:
                continue
            calendar.add_component(event.as_ical())
        return calendar

    def talks(self):
        return self.exclude(speaker='')


class Event(models.Model):
    day = models.DateField()
    venue = models.CharField(max_length=50)
    venue_url = models.URLField()
    start = models.TimeField()
    duration = models.PositiveIntegerField(default=60, help_text="In minutes")
    is_break = models.BooleanField(default=False)

    title = models.CharField(max_length=200, blank=True, help_text="Leave blank to create gaps in the schedule")
    speaker = models.CharField(max_length=100, blank=True)

    objects = EventQuerySet.as_manager()

    class Meta:
        ordering = ('day', 'start')

    @property
    def is_blank(self):
        return not self.title

    @property
    def day_grouping(self):
        """
        Used for grouping events by day, so that events starting after midnight
        still get grouped with the previous day.
        """
        if self.start.hour < 2:
            return self.day - timedelta(days=1)
        return self.day

    def get_css_class(self):
        classes = ['session']
        if self.is_break:
            classes.append('break')
        if self.duration != 60:
            classes.append('session-{}min'.format(self.duration))
        return ' '.join(classes)

    @property
    def dt_start(self):
        return timezone.make_aware(datetime.combine(self.day, self.start))

    @property
    def dt_end(self):
        return self.dt_start + timedelta(minutes=self.duration)

    @property
    def ical_uid(self):
        app, model = self._meta.label_lower.split('.')
        return "{}{}@2016.duth.rocks".format(model, self.pk)

    @property
    def ical_summary(self):
        if not self.speaker:
            return self.title
        return '{} - {}'.format(self.speaker, self.title)

    def as_ical(self):
        """
        Return a representation of the current talk as an icalendar.Event.
        """
        event = icalendar.Event()
        event.add("dtstart", self.dt_start)
        event.add("dtend", self.dt_end)
        event.add("uid", self.ical_uid)
        event.add("summary", self.ical_summary)
        event.add("location", "{}, Amsterdam, NL".format(self.venue))
        return event

schedule/views.py
from django.http import HttpResponse
from django.views.generic import ListView

from .models import Event


class ScheduleView(ListView):
    template_name = 'schedule/schedule.html'
    model = Event


class IcalTalkScheduleView(ScheduleView):
    def get_queryset(self):
        queryset = super(IcalTalkScheduleView, self).get_queryset()
        return queryset.talks()

    def get(self, request):
        calendar = self.get_queryset().as_ical()
        return HttpResponse(calendar.to_ical(),
                            content_type='text/calendar; charset=UTF-8')

schedule/templates/schedule/schedule.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<section id="schedule" class="row">
    <img src="{% static 'img/schedule-header.png' %}" class="header-image" alt="Schedule" />

    {% regroup object_list by day_grouping as by_day %}

    {% for gp in by_day %}
        <div class="col-md-6 day">
            <div class="header">
                <h3>{{ gp.grouper|date:'jS M, l' }}</h3>
                <p>Venue: <a href="{{ gp.list.0.venue_url }}" target="_blank">{{ gp.list.0.venue }}</a></p>
            </div>
            <div class="sessions">
                {% for event in gp.list %}
                    {% if event.is_blank %}
                        <div class="spacer-{{ event.duration }}min"></div>
                    {% else %}
                        <div class="{{ event.get_css_class }}">
                            <div class="datetime">{{ event.start|date:'G:i'}}</div>
                            <div class="session-details">
                                <p><b>{{ event.title|safe }}</b></p>
                                <p class="speaker">{{ event.speaker }}</p>
                            </div>
                            <div class="cls"></div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</section>
<div class="row pull-right" id="ical">
    <a class="btn btn-default btn-sm" href="{% url 'schedule:talks-ical' %}">
      <span class="glyphicon glyphicon-calendar"></span>
      iCal (talks only)
    </a>
</div>
{% endblock %}